<?php
/**
 * ActiveChannelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * rpc.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ActiveChannelTest Class Doc Comment
 *
 * @category    Class */
// * @description ActiveChannel
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ActiveChannelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ActiveChannel"
     */
    public function testActiveChannel()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "remote_pubkey"
     */
    public function testPropertyRemotePubkey()
    {
    }

    /**
     * Test attribute "channel_point"
     */
    public function testPropertyChannelPoint()
    {
    }

    /**
     * Test attribute "chan_id"
     */
    public function testPropertyChanId()
    {
    }

    /**
     * Test attribute "capacity"
     */
    public function testPropertyCapacity()
    {
    }

    /**
     * Test attribute "local_balance"
     */
    public function testPropertyLocalBalance()
    {
    }

    /**
     * Test attribute "remote_balance"
     */
    public function testPropertyRemoteBalance()
    {
    }

    /**
     * Test attribute "commit_fee"
     */
    public function testPropertyCommitFee()
    {
    }

    /**
     * Test attribute "commit_weight"
     */
    public function testPropertyCommitWeight()
    {
    }

    /**
     * Test attribute "fee_per_kw"
     */
    public function testPropertyFeePerKw()
    {
    }

    /**
     * Test attribute "unsettled_balance"
     */
    public function testPropertyUnsettledBalance()
    {
    }

    /**
     * Test attribute "total_satoshis_sent"
     */
    public function testPropertyTotalSatoshisSent()
    {
    }

    /**
     * Test attribute "total_satoshis_received"
     */
    public function testPropertyTotalSatoshisReceived()
    {
    }

    /**
     * Test attribute "num_updates"
     */
    public function testPropertyNumUpdates()
    {
    }

    /**
     * Test attribute "pending_htlcs"
     */
    public function testPropertyPendingHtlcs()
    {
    }

    /**
     * Test attribute "csv_delay"
     */
    public function testPropertyCsvDelay()
    {
    }
}
