<?php
/**
 * ChannelEdgeUpdateTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * rpc.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ChannelEdgeUpdateTest Class Doc Comment
 *
 * @category    Class */
// * @description ChannelEdgeUpdate
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ChannelEdgeUpdateTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ChannelEdgeUpdate"
     */
    public function testChannelEdgeUpdate()
    {
    }

    /**
     * Test attribute "chan_id"
     */
    public function testPropertyChanId()
    {
    }

    /**
     * Test attribute "chan_point"
     */
    public function testPropertyChanPoint()
    {
    }

    /**
     * Test attribute "capacity"
     */
    public function testPropertyCapacity()
    {
    }

    /**
     * Test attribute "routing_policy"
     */
    public function testPropertyRoutingPolicy()
    {
    }

    /**
     * Test attribute "advertising_node"
     */
    public function testPropertyAdvertisingNode()
    {
    }

    /**
     * Test attribute "connecting_node"
     */
    public function testPropertyConnectingNode()
    {
    }
}
