<?php
/**
 * GetInfoResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * rpc.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * GetInfoResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description GetInfoResponse
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetInfoResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GetInfoResponse"
     */
    public function testGetInfoResponse()
    {
    }

    /**
     * Test attribute "identity_pubkey"
     */
    public function testPropertyIdentityPubkey()
    {
    }

    /**
     * Test attribute "alias"
     */
    public function testPropertyAlias()
    {
    }

    /**
     * Test attribute "num_pending_channels"
     */
    public function testPropertyNumPendingChannels()
    {
    }

    /**
     * Test attribute "num_active_channels"
     */
    public function testPropertyNumActiveChannels()
    {
    }

    /**
     * Test attribute "num_peers"
     */
    public function testPropertyNumPeers()
    {
    }

    /**
     * Test attribute "block_height"
     */
    public function testPropertyBlockHeight()
    {
    }

    /**
     * Test attribute "block_hash"
     */
    public function testPropertyBlockHash()
    {
    }

    /**
     * Test attribute "synced_to_chain"
     */
    public function testPropertySyncedToChain()
    {
    }

    /**
     * Test attribute "testnet"
     */
    public function testPropertyTestnet()
    {
    }

    /**
     * Test attribute "chains"
     */
    public function testPropertyChains()
    {
    }
}
