<?php
/**
 * InvoiceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * rpc.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * InvoiceTest Class Doc Comment
 *
 * @category    Class */
// * @description Invoice
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InvoiceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Invoice"
     */
    public function testInvoice()
    {
    }

    /**
     * Test attribute "memo"
     */
    public function testPropertyMemo()
    {
    }

    /**
     * Test attribute "receipt"
     */
    public function testPropertyReceipt()
    {
    }

    /**
     * Test attribute "r_preimage"
     */
    public function testPropertyRPreimage()
    {
    }

    /**
     * Test attribute "r_hash"
     */
    public function testPropertyRHash()
    {
    }

    /**
     * Test attribute "value"
     */
    public function testPropertyValue()
    {
    }

    /**
     * Test attribute "settled"
     */
    public function testPropertySettled()
    {
    }

    /**
     * Test attribute "creation_date"
     */
    public function testPropertyCreationDate()
    {
    }

    /**
     * Test attribute "settle_date"
     */
    public function testPropertySettleDate()
    {
    }

    /**
     * Test attribute "payment_request"
     */
    public function testPropertyPaymentRequest()
    {
    }

    /**
     * Test attribute "description_hash"
     */
    public function testPropertyDescriptionHash()
    {
    }

    /**
     * Test attribute "expiry"
     */
    public function testPropertyExpiry()
    {
    }

    /**
     * Test attribute "fallback_addr"
     */
    public function testPropertyFallbackAddr()
    {
    }

    /**
     * Test attribute "cltv_expiry"
     */
    public function testPropertyCltvExpiry()
    {
    }
}
