<?php
/**
 * NetworkInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * rpc.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * NetworkInfoTest Class Doc Comment
 *
 * @category    Class */
// * @description NetworkInfo
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class NetworkInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "NetworkInfo"
     */
    public function testNetworkInfo()
    {
    }

    /**
     * Test attribute "graph_diameter"
     */
    public function testPropertyGraphDiameter()
    {
    }

    /**
     * Test attribute "avg_out_degree"
     */
    public function testPropertyAvgOutDegree()
    {
    }

    /**
     * Test attribute "max_out_degree"
     */
    public function testPropertyMaxOutDegree()
    {
    }

    /**
     * Test attribute "num_nodes"
     */
    public function testPropertyNumNodes()
    {
    }

    /**
     * Test attribute "num_channels"
     */
    public function testPropertyNumChannels()
    {
    }

    /**
     * Test attribute "total_network_capacity"
     */
    public function testPropertyTotalNetworkCapacity()
    {
    }

    /**
     * Test attribute "avg_channel_size"
     */
    public function testPropertyAvgChannelSize()
    {
    }

    /**
     * Test attribute "min_channel_size"
     */
    public function testPropertyMinChannelSize()
    {
    }

    /**
     * Test attribute "max_channel_size"
     */
    public function testPropertyMaxChannelSize()
    {
    }
}
