<?php
/**
 * NodeUpdateTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * rpc.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * NodeUpdateTest Class Doc Comment
 *
 * @category    Class */
// * @description NodeUpdate
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class NodeUpdateTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "NodeUpdate"
     */
    public function testNodeUpdate()
    {
    }

    /**
     * Test attribute "addresses"
     */
    public function testPropertyAddresses()
    {
    }

    /**
     * Test attribute "identity_key"
     */
    public function testPropertyIdentityKey()
    {
    }

    /**
     * Test attribute "global_features"
     */
    public function testPropertyGlobalFeatures()
    {
    }

    /**
     * Test attribute "alias"
     */
    public function testPropertyAlias()
    {
    }
}
