<?php
/**
 * OpenChannelRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * rpc.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * OpenChannelRequestTest Class Doc Comment
 *
 * @category    Class */
// * @description OpenChannelRequest
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OpenChannelRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OpenChannelRequest"
     */
    public function testOpenChannelRequest()
    {
    }

    /**
     * Test attribute "target_peer_id"
     */
    public function testPropertyTargetPeerId()
    {
    }

    /**
     * Test attribute "node_pubkey"
     */
    public function testPropertyNodePubkey()
    {
    }

    /**
     * Test attribute "node_pubkey_string"
     */
    public function testPropertyNodePubkeyString()
    {
    }

    /**
     * Test attribute "local_funding_amount"
     */
    public function testPropertyLocalFundingAmount()
    {
    }

    /**
     * Test attribute "push_sat"
     */
    public function testPropertyPushSat()
    {
    }

    /**
     * Test attribute "target_conf"
     */
    public function testPropertyTargetConf()
    {
    }

    /**
     * Test attribute "sat_per_byte"
     */
    public function testPropertySatPerByte()
    {
    }

    /**
     * Test attribute "private"
     */
    public function testPropertyPrivate()
    {
    }
}
