<?php
/**
 * PeerTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * rpc.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PeerTest Class Doc Comment
 *
 * @category    Class */
// * @description Peer
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PeerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Peer"
     */
    public function testPeer()
    {
    }

    /**
     * Test attribute "pub_key"
     */
    public function testPropertyPubKey()
    {
    }

    /**
     * Test attribute "peer_id"
     */
    public function testPropertyPeerId()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "bytes_sent"
     */
    public function testPropertyBytesSent()
    {
    }

    /**
     * Test attribute "bytes_recv"
     */
    public function testPropertyBytesRecv()
    {
    }

    /**
     * Test attribute "sat_sent"
     */
    public function testPropertySatSent()
    {
    }

    /**
     * Test attribute "sat_recv"
     */
    public function testPropertySatRecv()
    {
    }

    /**
     * Test attribute "inbound"
     */
    public function testPropertyInbound()
    {
    }

    /**
     * Test attribute "ping_time"
     */
    public function testPropertyPingTime()
    {
    }
}
