<?php
/**
 * PendingChannelResponsePendingOpenChannelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * rpc.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PendingChannelResponsePendingOpenChannelTest Class Doc Comment
 *
 * @category    Class */
// * @description PendingChannelResponsePendingOpenChannel
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PendingChannelResponsePendingOpenChannelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PendingChannelResponsePendingOpenChannel"
     */
    public function testPendingChannelResponsePendingOpenChannel()
    {
    }

    /**
     * Test attribute "channel"
     */
    public function testPropertyChannel()
    {
    }

    /**
     * Test attribute "confirmation_height"
     */
    public function testPropertyConfirmationHeight()
    {
    }

    /**
     * Test attribute "blocks_till_open"
     */
    public function testPropertyBlocksTillOpen()
    {
    }

    /**
     * Test attribute "commit_fee"
     */
    public function testPropertyCommitFee()
    {
    }

    /**
     * Test attribute "commit_weight"
     */
    public function testPropertyCommitWeight()
    {
    }

    /**
     * Test attribute "fee_per_kw"
     */
    public function testPropertyFeePerKw()
    {
    }
}
