<?php
/**
 * PendingChannelResponseForceClosedChannelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * rpc.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PendingChannelResponseForceClosedChannelTest Class Doc Comment
 *
 * @category    Class */
// * @description PendingChannelResponseForceClosedChannel
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PendingChannelResponseForceClosedChannelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PendingChannelResponseForceClosedChannel"
     */
    public function testPendingChannelResponseForceClosedChannel()
    {
    }

    /**
     * Test attribute "channel"
     */
    public function testPropertyChannel()
    {
    }

    /**
     * Test attribute "closing_txid"
     */
    public function testPropertyClosingTxid()
    {
    }

    /**
     * Test attribute "limbo_balance"
     */
    public function testPropertyLimboBalance()
    {
    }

    /**
     * Test attribute "maturity_height"
     */
    public function testPropertyMaturityHeight()
    {
    }

    /**
     * Test attribute "blocks_til_maturity"
     */
    public function testPropertyBlocksTilMaturity()
    {
    }

    /**
     * Test attribute "recovered_balance"
     */
    public function testPropertyRecoveredBalance()
    {
    }

    /**
     * Test attribute "pending_htlcs"
     */
    public function testPropertyPendingHtlcs()
    {
    }
}
