<?php
/**
 * RoutingPolicyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * rpc.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * RoutingPolicyTest Class Doc Comment
 *
 * @category    Class */
// * @description RoutingPolicy
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RoutingPolicyTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RoutingPolicy"
     */
    public function testRoutingPolicy()
    {
    }

    /**
     * Test attribute "time_lock_delta"
     */
    public function testPropertyTimeLockDelta()
    {
    }

    /**
     * Test attribute "min_htlc"
     */
    public function testPropertyMinHtlc()
    {
    }

    /**
     * Test attribute "fee_base_msat"
     */
    public function testPropertyFeeBaseMsat()
    {
    }

    /**
     * Test attribute "fee_rate_milli_msat"
     */
    public function testPropertyFeeRateMilliMsat()
    {
    }
}
