<?php
/**
 * TransactionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * rpc.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TransactionTest Class Doc Comment
 *
 * @category    Class */
// * @description Transaction
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TransactionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Transaction"
     */
    public function testTransaction()
    {
    }

    /**
     * Test attribute "tx_hash"
     */
    public function testPropertyTxHash()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "num_confirmations"
     */
    public function testPropertyNumConfirmations()
    {
    }

    /**
     * Test attribute "block_hash"
     */
    public function testPropertyBlockHash()
    {
    }

    /**
     * Test attribute "block_height"
     */
    public function testPropertyBlockHeight()
    {
    }

    /**
     * Test attribute "time_stamp"
     */
    public function testPropertyTimeStamp()
    {
    }

    /**
     * Test attribute "total_fees"
     */
    public function testPropertyTotalFees()
    {
    }

    /**
     * Test attribute "dest_addresses"
     */
    public function testPropertyDestAddresses()
    {
    }
}
