<?php
/**
 * Invoice
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * rpc.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * Invoice Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Invoice implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Invoice';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'memo' => 'string',
        'receipt' => 'string',
        'r_preimage' => 'string',
        'r_hash' => 'string',
        'value' => 'string',
        'settled' => 'bool',
        'creation_date' => 'string',
        'settle_date' => 'string',
        'payment_request' => 'string',
        'description_hash' => 'string',
        'expiry' => 'string',
        'fallback_addr' => 'string',
        'cltv_expiry' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'memo' => null,
        'receipt' => 'byte',
        'r_preimage' => 'byte',
        'r_hash' => 'byte',
        'value' => 'int64',
        'settled' => 'boolean',
        'creation_date' => 'int64',
        'settle_date' => 'int64',
        'payment_request' => null,
        'description_hash' => 'byte',
        'expiry' => 'int64',
        'fallback_addr' => null,
        'cltv_expiry' => 'uint64'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'memo' => 'memo',
        'receipt' => 'receipt',
        'r_preimage' => 'r_preimage',
        'r_hash' => 'r_hash',
        'value' => 'value',
        'settled' => 'settled',
        'creation_date' => 'creation_date',
        'settle_date' => 'settle_date',
        'payment_request' => 'payment_request',
        'description_hash' => 'description_hash',
        'expiry' => 'expiry',
        'fallback_addr' => 'fallback_addr',
        'cltv_expiry' => 'cltv_expiry'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'memo' => 'setMemo',
        'receipt' => 'setReceipt',
        'r_preimage' => 'setRPreimage',
        'r_hash' => 'setRHash',
        'value' => 'setValue',
        'settled' => 'setSettled',
        'creation_date' => 'setCreationDate',
        'settle_date' => 'setSettleDate',
        'payment_request' => 'setPaymentRequest',
        'description_hash' => 'setDescriptionHash',
        'expiry' => 'setExpiry',
        'fallback_addr' => 'setFallbackAddr',
        'cltv_expiry' => 'setCltvExpiry'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'memo' => 'getMemo',
        'receipt' => 'getReceipt',
        'r_preimage' => 'getRPreimage',
        'r_hash' => 'getRHash',
        'value' => 'getValue',
        'settled' => 'getSettled',
        'creation_date' => 'getCreationDate',
        'settle_date' => 'getSettleDate',
        'payment_request' => 'getPaymentRequest',
        'description_hash' => 'getDescriptionHash',
        'expiry' => 'getExpiry',
        'fallback_addr' => 'getFallbackAddr',
        'cltv_expiry' => 'getCltvExpiry'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['memo'] = isset($data['memo']) ? $data['memo'] : null;
        $this->container['receipt'] = isset($data['receipt']) ? $data['receipt'] : null;
        $this->container['r_preimage'] = isset($data['r_preimage']) ? $data['r_preimage'] : null;
        $this->container['r_hash'] = isset($data['r_hash']) ? $data['r_hash'] : null;
        $this->container['value'] = isset($data['value']) ? $data['value'] : null;
        $this->container['settled'] = isset($data['settled']) ? $data['settled'] : null;
        $this->container['creation_date'] = isset($data['creation_date']) ? $data['creation_date'] : null;
        $this->container['settle_date'] = isset($data['settle_date']) ? $data['settle_date'] : null;
        $this->container['payment_request'] = isset($data['payment_request']) ? $data['payment_request'] : null;
        $this->container['description_hash'] = isset($data['description_hash']) ? $data['description_hash'] : null;
        $this->container['expiry'] = isset($data['expiry']) ? $data['expiry'] : null;
        $this->container['fallback_addr'] = isset($data['fallback_addr']) ? $data['fallback_addr'] : null;
        $this->container['cltv_expiry'] = isset($data['cltv_expiry']) ? $data['cltv_expiry'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['receipt']) && !preg_match("/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/", $this->container['receipt'])) {
            $invalidProperties[] = "invalid value for 'receipt', must be conform to the pattern /^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/.";
        }

        if (!is_null($this->container['r_preimage']) && !preg_match("/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/", $this->container['r_preimage'])) {
            $invalidProperties[] = "invalid value for 'r_preimage', must be conform to the pattern /^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/.";
        }

        if (!is_null($this->container['r_hash']) && !preg_match("/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/", $this->container['r_hash'])) {
            $invalidProperties[] = "invalid value for 'r_hash', must be conform to the pattern /^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/.";
        }

        if (!is_null($this->container['description_hash']) && !preg_match("/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/", $this->container['description_hash'])) {
            $invalidProperties[] = "invalid value for 'description_hash', must be conform to the pattern /^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if (!preg_match("/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/", $this->container['receipt'])) {
            return false;
        }
        if (!preg_match("/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/", $this->container['r_preimage'])) {
            return false;
        }
        if (!preg_match("/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/", $this->container['r_hash'])) {
            return false;
        }
        if (!preg_match("/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/", $this->container['description_hash'])) {
            return false;
        }
        return true;
    }


    /**
     * Gets memo
     *
     * @return string
     */
    public function getMemo()
    {
        return $this->container['memo'];
    }

    /**
     * Sets memo
     *
     * @param string $memo * An optional memo to attach along with the invoice. Used for record keeping purposes for the invoice's creator, and will also be set in the description field of the encoded payment request if the description_hash field is not being used.
     *
     * @return $this
     */
    public function setMemo($memo)
    {
        $this->container['memo'] = $memo;

        return $this;
    }

    /**
     * Gets receipt
     *
     * @return string
     */
    public function getReceipt()
    {
        return $this->container['receipt'];
    }

    /**
     * Sets receipt
     *
     * @param string $receipt receipt
     *
     * @return $this
     */
    public function setReceipt($receipt)
    {

        if (!is_null($receipt) && (!preg_match("/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/", $receipt))) {
            throw new \InvalidArgumentException("invalid value for $receipt when calling Invoice., must conform to the pattern /^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/.");
        }

        $this->container['receipt'] = $receipt;

        return $this;
    }

    /**
     * Gets r_preimage
     *
     * @return string
     */
    public function getRPreimage()
    {
        return $this->container['r_preimage'];
    }

    /**
     * Sets r_preimage
     *
     * @param string $r_preimage r_preimage
     *
     * @return $this
     */
    public function setRPreimage($r_preimage)
    {

        if (!is_null($r_preimage) && (!preg_match("/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/", $r_preimage))) {
            throw new \InvalidArgumentException("invalid value for $r_preimage when calling Invoice., must conform to the pattern /^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/.");
        }

        $this->container['r_preimage'] = $r_preimage;

        return $this;
    }

    /**
     * Gets r_hash
     *
     * @return string
     */
    public function getRHash()
    {
        return $this->container['r_hash'];
    }

    /**
     * Sets r_hash
     *
     * @param string $r_hash r_hash
     *
     * @return $this
     */
    public function setRHash($r_hash)
    {

        if (!is_null($r_hash) && (!preg_match("/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/", $r_hash))) {
            throw new \InvalidArgumentException("invalid value for $r_hash when calling Invoice., must conform to the pattern /^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/.");
        }

        $this->container['r_hash'] = $r_hash;

        return $this;
    }

    /**
     * Gets value
     *
     * @return string
     */
    public function getValue()
    {
        return $this->container['value'];
    }

    /**
     * Sets value
     *
     * @param string $value value
     *
     * @return $this
     */
    public function setValue($value)
    {
        $this->container['value'] = $value;

        return $this;
    }

    /**
     * Gets settled
     *
     * @return bool
     */
    public function getSettled()
    {
        return $this->container['settled'];
    }

    /**
     * Sets settled
     *
     * @param bool $settled settled
     *
     * @return $this
     */
    public function setSettled($settled)
    {
        $this->container['settled'] = $settled;

        return $this;
    }

    /**
     * Gets creation_date
     *
     * @return string
     */
    public function getCreationDate()
    {
        return $this->container['creation_date'];
    }

    /**
     * Sets creation_date
     *
     * @param string $creation_date creation_date
     *
     * @return $this
     */
    public function setCreationDate($creation_date)
    {
        $this->container['creation_date'] = $creation_date;

        return $this;
    }

    /**
     * Gets settle_date
     *
     * @return string
     */
    public function getSettleDate()
    {
        return $this->container['settle_date'];
    }

    /**
     * Sets settle_date
     *
     * @param string $settle_date settle_date
     *
     * @return $this
     */
    public function setSettleDate($settle_date)
    {
        $this->container['settle_date'] = $settle_date;

        return $this;
    }

    /**
     * Gets payment_request
     *
     * @return string
     */
    public function getPaymentRequest()
    {
        return $this->container['payment_request'];
    }

    /**
     * Sets payment_request
     *
     * @param string $payment_request * A bare-bones invoice for a payment within the Lightning Network.  With the details of the invoice, the sender has all the data necessary to send a payment to the recipient.
     *
     * @return $this
     */
    public function setPaymentRequest($payment_request)
    {
        $this->container['payment_request'] = $payment_request;

        return $this;
    }

    /**
     * Gets description_hash
     *
     * @return string
     */
    public function getDescriptionHash()
    {
        return $this->container['description_hash'];
    }

    /**
     * Sets description_hash
     *
     * @param string $description_hash * Hash (SHA-256) of a description of the payment. Used if the description of payment (memo) is too long to naturally fit within the description field of an encoded payment request.
     *
     * @return $this
     */
    public function setDescriptionHash($description_hash)
    {

        if (!is_null($description_hash) && (!preg_match("/^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/", $description_hash))) {
            throw new \InvalidArgumentException("invalid value for $description_hash when calling Invoice., must conform to the pattern /^(?:[A-Za-z0-9+\/]{4})*(?:[A-Za-z0-9+\/]{2}==|[A-Za-z0-9+\/]{3}=)?$/.");
        }

        $this->container['description_hash'] = $description_hash;

        return $this;
    }

    /**
     * Gets expiry
     *
     * @return string
     */
    public function getExpiry()
    {
        return $this->container['expiry'];
    }

    /**
     * Sets expiry
     *
     * @param string $expiry / Payment request expiry time in seconds. Default is 3600 (1 hour).
     *
     * @return $this
     */
    public function setExpiry($expiry)
    {
        $this->container['expiry'] = $expiry;

        return $this;
    }

    /**
     * Gets fallback_addr
     *
     * @return string
     */
    public function getFallbackAddr()
    {
        return $this->container['fallback_addr'];
    }

    /**
     * Sets fallback_addr
     *
     * @param string $fallback_addr / Fallback on-chain address.
     *
     * @return $this
     */
    public function setFallbackAddr($fallback_addr)
    {
        $this->container['fallback_addr'] = $fallback_addr;

        return $this;
    }

    /**
     * Gets cltv_expiry
     *
     * @return string
     */
    public function getCltvExpiry()
    {
        return $this->container['cltv_expiry'];
    }

    /**
     * Sets cltv_expiry
     *
     * @param string $cltv_expiry / Delta to use for the time-lock of the CLTV extended to the final hop.
     *
     * @return $this
     */
    public function setCltvExpiry($cltv_expiry)
    {
        $this->container['cltv_expiry'] = $cltv_expiry;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


