<?php
/**
 * PayReq
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * rpc.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * PayReq Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PayReq implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'PayReq';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'destination' => 'string',
        'payment_hash' => 'string',
        'num_satoshis' => 'string',
        'timestamp' => 'string',
        'expiry' => 'string',
        'description' => 'string',
        'description_hash' => 'string',
        'fallback_addr' => 'string',
        'cltv_expiry' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'destination' => null,
        'payment_hash' => null,
        'num_satoshis' => 'int64',
        'timestamp' => 'int64',
        'expiry' => 'int64',
        'description' => null,
        'description_hash' => null,
        'fallback_addr' => null,
        'cltv_expiry' => 'int64'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'destination' => 'destination',
        'payment_hash' => 'payment_hash',
        'num_satoshis' => 'num_satoshis',
        'timestamp' => 'timestamp',
        'expiry' => 'expiry',
        'description' => 'description',
        'description_hash' => 'description_hash',
        'fallback_addr' => 'fallback_addr',
        'cltv_expiry' => 'cltv_expiry'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'destination' => 'setDestination',
        'payment_hash' => 'setPaymentHash',
        'num_satoshis' => 'setNumSatoshis',
        'timestamp' => 'setTimestamp',
        'expiry' => 'setExpiry',
        'description' => 'setDescription',
        'description_hash' => 'setDescriptionHash',
        'fallback_addr' => 'setFallbackAddr',
        'cltv_expiry' => 'setCltvExpiry'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'destination' => 'getDestination',
        'payment_hash' => 'getPaymentHash',
        'num_satoshis' => 'getNumSatoshis',
        'timestamp' => 'getTimestamp',
        'expiry' => 'getExpiry',
        'description' => 'getDescription',
        'description_hash' => 'getDescriptionHash',
        'fallback_addr' => 'getFallbackAddr',
        'cltv_expiry' => 'getCltvExpiry'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['destination'] = isset($data['destination']) ? $data['destination'] : null;
        $this->container['payment_hash'] = isset($data['payment_hash']) ? $data['payment_hash'] : null;
        $this->container['num_satoshis'] = isset($data['num_satoshis']) ? $data['num_satoshis'] : null;
        $this->container['timestamp'] = isset($data['timestamp']) ? $data['timestamp'] : null;
        $this->container['expiry'] = isset($data['expiry']) ? $data['expiry'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['description_hash'] = isset($data['description_hash']) ? $data['description_hash'] : null;
        $this->container['fallback_addr'] = isset($data['fallback_addr']) ? $data['fallback_addr'] : null;
        $this->container['cltv_expiry'] = isset($data['cltv_expiry']) ? $data['cltv_expiry'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets destination
     *
     * @return string
     */
    public function getDestination()
    {
        return $this->container['destination'];
    }

    /**
     * Sets destination
     *
     * @param string $destination destination
     *
     * @return $this
     */
    public function setDestination($destination)
    {
        $this->container['destination'] = $destination;

        return $this;
    }

    /**
     * Gets payment_hash
     *
     * @return string
     */
    public function getPaymentHash()
    {
        return $this->container['payment_hash'];
    }

    /**
     * Sets payment_hash
     *
     * @param string $payment_hash payment_hash
     *
     * @return $this
     */
    public function setPaymentHash($payment_hash)
    {
        $this->container['payment_hash'] = $payment_hash;

        return $this;
    }

    /**
     * Gets num_satoshis
     *
     * @return string
     */
    public function getNumSatoshis()
    {
        return $this->container['num_satoshis'];
    }

    /**
     * Sets num_satoshis
     *
     * @param string $num_satoshis num_satoshis
     *
     * @return $this
     */
    public function setNumSatoshis($num_satoshis)
    {
        $this->container['num_satoshis'] = $num_satoshis;

        return $this;
    }

    /**
     * Gets timestamp
     *
     * @return string
     */
    public function getTimestamp()
    {
        return $this->container['timestamp'];
    }

    /**
     * Sets timestamp
     *
     * @param string $timestamp timestamp
     *
     * @return $this
     */
    public function setTimestamp($timestamp)
    {
        $this->container['timestamp'] = $timestamp;

        return $this;
    }

    /**
     * Gets expiry
     *
     * @return string
     */
    public function getExpiry()
    {
        return $this->container['expiry'];
    }

    /**
     * Sets expiry
     *
     * @param string $expiry expiry
     *
     * @return $this
     */
    public function setExpiry($expiry)
    {
        $this->container['expiry'] = $expiry;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description description
     *
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets description_hash
     *
     * @return string
     */
    public function getDescriptionHash()
    {
        return $this->container['description_hash'];
    }

    /**
     * Sets description_hash
     *
     * @param string $description_hash description_hash
     *
     * @return $this
     */
    public function setDescriptionHash($description_hash)
    {
        $this->container['description_hash'] = $description_hash;

        return $this;
    }

    /**
     * Gets fallback_addr
     *
     * @return string
     */
    public function getFallbackAddr()
    {
        return $this->container['fallback_addr'];
    }

    /**
     * Sets fallback_addr
     *
     * @param string $fallback_addr fallback_addr
     *
     * @return $this
     */
    public function setFallbackAddr($fallback_addr)
    {
        $this->container['fallback_addr'] = $fallback_addr;

        return $this;
    }

    /**
     * Gets cltv_expiry
     *
     * @return string
     */
    public function getCltvExpiry()
    {
        return $this->container['cltv_expiry'];
    }

    /**
     * Sets cltv_expiry
     *
     * @param string $cltv_expiry cltv_expiry
     *
     * @return $this
     */
    public function setCltvExpiry($cltv_expiry)
    {
        $this->container['cltv_expiry'] = $cltv_expiry;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


