<?php
/**
 * PendingChannelResponsePendingChannel
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * rpc.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * PendingChannelResponsePendingChannel Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PendingChannelResponsePendingChannel implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'PendingChannelResponsePendingChannel';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'remote_node_pub' => 'string',
        'channel_point' => 'string',
        'capacity' => 'string',
        'local_balance' => 'string',
        'remote_balance' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'remote_node_pub' => null,
        'channel_point' => null,
        'capacity' => 'int64',
        'local_balance' => 'int64',
        'remote_balance' => 'int64'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'remote_node_pub' => 'remote_node_pub',
        'channel_point' => 'channel_point',
        'capacity' => 'capacity',
        'local_balance' => 'local_balance',
        'remote_balance' => 'remote_balance'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'remote_node_pub' => 'setRemoteNodePub',
        'channel_point' => 'setChannelPoint',
        'capacity' => 'setCapacity',
        'local_balance' => 'setLocalBalance',
        'remote_balance' => 'setRemoteBalance'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'remote_node_pub' => 'getRemoteNodePub',
        'channel_point' => 'getChannelPoint',
        'capacity' => 'getCapacity',
        'local_balance' => 'getLocalBalance',
        'remote_balance' => 'getRemoteBalance'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['remote_node_pub'] = isset($data['remote_node_pub']) ? $data['remote_node_pub'] : null;
        $this->container['channel_point'] = isset($data['channel_point']) ? $data['channel_point'] : null;
        $this->container['capacity'] = isset($data['capacity']) ? $data['capacity'] : null;
        $this->container['local_balance'] = isset($data['local_balance']) ? $data['local_balance'] : null;
        $this->container['remote_balance'] = isset($data['remote_balance']) ? $data['remote_balance'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets remote_node_pub
     *
     * @return string
     */
    public function getRemoteNodePub()
    {
        return $this->container['remote_node_pub'];
    }

    /**
     * Sets remote_node_pub
     *
     * @param string $remote_node_pub remote_node_pub
     *
     * @return $this
     */
    public function setRemoteNodePub($remote_node_pub)
    {
        $this->container['remote_node_pub'] = $remote_node_pub;

        return $this;
    }

    /**
     * Gets channel_point
     *
     * @return string
     */
    public function getChannelPoint()
    {
        return $this->container['channel_point'];
    }

    /**
     * Sets channel_point
     *
     * @param string $channel_point channel_point
     *
     * @return $this
     */
    public function setChannelPoint($channel_point)
    {
        $this->container['channel_point'] = $channel_point;

        return $this;
    }

    /**
     * Gets capacity
     *
     * @return string
     */
    public function getCapacity()
    {
        return $this->container['capacity'];
    }

    /**
     * Sets capacity
     *
     * @param string $capacity capacity
     *
     * @return $this
     */
    public function setCapacity($capacity)
    {
        $this->container['capacity'] = $capacity;

        return $this;
    }

    /**
     * Gets local_balance
     *
     * @return string
     */
    public function getLocalBalance()
    {
        return $this->container['local_balance'];
    }

    /**
     * Sets local_balance
     *
     * @param string $local_balance local_balance
     *
     * @return $this
     */
    public function setLocalBalance($local_balance)
    {
        $this->container['local_balance'] = $local_balance;

        return $this;
    }

    /**
     * Gets remote_balance
     *
     * @return string
     */
    public function getRemoteBalance()
    {
        return $this->container['remote_balance'];
    }

    /**
     * Sets remote_balance
     *
     * @param string $remote_balance remote_balance
     *
     * @return $this
     */
    public function setRemoteBalance($remote_balance)
    {
        $this->container['remote_balance'] = $remote_balance;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


