<?php
/**
 * PendingChannelResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * rpc.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * PendingChannelResponse Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PendingChannelResponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'PendingChannelResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'total_limbo_balance' => 'string',
        'pending_open_channels' => '\Swagger\Client\Model\PendingChannelResponsePendingOpenChannel[]',
        'pending_closing_channels' => '\Swagger\Client\Model\PendingChannelResponseClosedChannel[]',
        'pending_force_closing_channels' => '\Swagger\Client\Model\PendingChannelResponseForceClosedChannel[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'total_limbo_balance' => 'int64',
        'pending_open_channels' => null,
        'pending_closing_channels' => null,
        'pending_force_closing_channels' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'total_limbo_balance' => 'total_limbo_balance',
        'pending_open_channels' => 'pending_open_channels',
        'pending_closing_channels' => 'pending_closing_channels',
        'pending_force_closing_channels' => 'pending_force_closing_channels'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'total_limbo_balance' => 'setTotalLimboBalance',
        'pending_open_channels' => 'setPendingOpenChannels',
        'pending_closing_channels' => 'setPendingClosingChannels',
        'pending_force_closing_channels' => 'setPendingForceClosingChannels'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'total_limbo_balance' => 'getTotalLimboBalance',
        'pending_open_channels' => 'getPendingOpenChannels',
        'pending_closing_channels' => 'getPendingClosingChannels',
        'pending_force_closing_channels' => 'getPendingForceClosingChannels'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['total_limbo_balance'] = isset($data['total_limbo_balance']) ? $data['total_limbo_balance'] : null;
        $this->container['pending_open_channels'] = isset($data['pending_open_channels']) ? $data['pending_open_channels'] : null;
        $this->container['pending_closing_channels'] = isset($data['pending_closing_channels']) ? $data['pending_closing_channels'] : null;
        $this->container['pending_force_closing_channels'] = isset($data['pending_force_closing_channels']) ? $data['pending_force_closing_channels'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets total_limbo_balance
     *
     * @return string
     */
    public function getTotalLimboBalance()
    {
        return $this->container['total_limbo_balance'];
    }

    /**
     * Sets total_limbo_balance
     *
     * @param string $total_limbo_balance total_limbo_balance
     *
     * @return $this
     */
    public function setTotalLimboBalance($total_limbo_balance)
    {
        $this->container['total_limbo_balance'] = $total_limbo_balance;

        return $this;
    }

    /**
     * Gets pending_open_channels
     *
     * @return \Swagger\Client\Model\PendingChannelResponsePendingOpenChannel[]
     */
    public function getPendingOpenChannels()
    {
        return $this->container['pending_open_channels'];
    }

    /**
     * Sets pending_open_channels
     *
     * @param \Swagger\Client\Model\PendingChannelResponsePendingOpenChannel[] $pending_open_channels pending_open_channels
     *
     * @return $this
     */
    public function setPendingOpenChannels($pending_open_channels)
    {
        $this->container['pending_open_channels'] = $pending_open_channels;

        return $this;
    }

    /**
     * Gets pending_closing_channels
     *
     * @return \Swagger\Client\Model\PendingChannelResponseClosedChannel[]
     */
    public function getPendingClosingChannels()
    {
        return $this->container['pending_closing_channels'];
    }

    /**
     * Sets pending_closing_channels
     *
     * @param \Swagger\Client\Model\PendingChannelResponseClosedChannel[] $pending_closing_channels pending_closing_channels
     *
     * @return $this
     */
    public function setPendingClosingChannels($pending_closing_channels)
    {
        $this->container['pending_closing_channels'] = $pending_closing_channels;

        return $this;
    }

    /**
     * Gets pending_force_closing_channels
     *
     * @return \Swagger\Client\Model\PendingChannelResponseForceClosedChannel[]
     */
    public function getPendingForceClosingChannels()
    {
        return $this->container['pending_force_closing_channels'];
    }

    /**
     * Sets pending_force_closing_channels
     *
     * @param \Swagger\Client\Model\PendingChannelResponseForceClosedChannel[] $pending_force_closing_channels pending_force_closing_channels
     *
     * @return $this
     */
    public function setPendingForceClosingChannels($pending_force_closing_channels)
    {
        $this->container['pending_force_closing_channels'] = $pending_force_closing_channels;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


