<?php
/**
 * RoutingPolicy
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * rpc.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: version not set
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * RoutingPolicy Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RoutingPolicy implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'RoutingPolicy';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'time_lock_delta' => 'int',
        'min_htlc' => 'string',
        'fee_base_msat' => 'string',
        'fee_rate_milli_msat' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'time_lock_delta' => 'int64',
        'min_htlc' => 'int64',
        'fee_base_msat' => 'int64',
        'fee_rate_milli_msat' => 'int64'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'time_lock_delta' => 'time_lock_delta',
        'min_htlc' => 'min_htlc',
        'fee_base_msat' => 'fee_base_msat',
        'fee_rate_milli_msat' => 'fee_rate_milli_msat'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'time_lock_delta' => 'setTimeLockDelta',
        'min_htlc' => 'setMinHtlc',
        'fee_base_msat' => 'setFeeBaseMsat',
        'fee_rate_milli_msat' => 'setFeeRateMilliMsat'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'time_lock_delta' => 'getTimeLockDelta',
        'min_htlc' => 'getMinHtlc',
        'fee_base_msat' => 'getFeeBaseMsat',
        'fee_rate_milli_msat' => 'getFeeRateMilliMsat'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['time_lock_delta'] = isset($data['time_lock_delta']) ? $data['time_lock_delta'] : null;
        $this->container['min_htlc'] = isset($data['min_htlc']) ? $data['min_htlc'] : null;
        $this->container['fee_base_msat'] = isset($data['fee_base_msat']) ? $data['fee_base_msat'] : null;
        $this->container['fee_rate_milli_msat'] = isset($data['fee_rate_milli_msat']) ? $data['fee_rate_milli_msat'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets time_lock_delta
     *
     * @return int
     */
    public function getTimeLockDelta()
    {
        return $this->container['time_lock_delta'];
    }

    /**
     * Sets time_lock_delta
     *
     * @param int $time_lock_delta time_lock_delta
     *
     * @return $this
     */
    public function setTimeLockDelta($time_lock_delta)
    {
        $this->container['time_lock_delta'] = $time_lock_delta;

        return $this;
    }

    /**
     * Gets min_htlc
     *
     * @return string
     */
    public function getMinHtlc()
    {
        return $this->container['min_htlc'];
    }

    /**
     * Sets min_htlc
     *
     * @param string $min_htlc min_htlc
     *
     * @return $this
     */
    public function setMinHtlc($min_htlc)
    {
        $this->container['min_htlc'] = $min_htlc;

        return $this;
    }

    /**
     * Gets fee_base_msat
     *
     * @return string
     */
    public function getFeeBaseMsat()
    {
        return $this->container['fee_base_msat'];
    }

    /**
     * Sets fee_base_msat
     *
     * @param string $fee_base_msat fee_base_msat
     *
     * @return $this
     */
    public function setFeeBaseMsat($fee_base_msat)
    {
        $this->container['fee_base_msat'] = $fee_base_msat;

        return $this;
    }

    /**
     * Gets fee_rate_milli_msat
     *
     * @return string
     */
    public function getFeeRateMilliMsat()
    {
        return $this->container['fee_rate_milli_msat'];
    }

    /**
     * Sets fee_rate_milli_msat
     *
     * @param string $fee_rate_milli_msat fee_rate_milli_msat
     *
     * @return $this
     */
    public function setFeeRateMilliMsat($fee_rate_milli_msat)
    {
        $this->container['fee_rate_milli_msat'] = $fee_rate_milli_msat;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


